apiVersion: 123
kind: Deployment
metadata:
  name: Pico
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nico-nginx
      nico: yo
  template:
    metadata:
      name: nico-nginx
      labels:
        app: nico-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: false