apiVersion: 123
kind: Deployment
metadata:
  name: Nico
spec:
  selector:
    matchLabels:
      app: nico-nginx
      nico: yo
  template:
    metadata:
      name: nico-nginx
      labels:
        app: nico-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
        - name: pichon
          image: alpine
          ports:
            - containerPort: 20
              hostPort: 8050
